language: emacs-lisp

env:
  matrix:
    - EMACS=emacs24

install:
  - if [ "$EMACS" = "emacs24"  ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi

script:
  ./util/run-tests.sh $EMACS
